### ISSUE TITLE
Visualization demo?

### ISSUE THREAD

**Issue by wjn922** [ksaito-ut/openworld_ldet#2]
Hi,

Would you plz give some instructions on how to visualize the LDET results?

**Comment by ksaito-ut** [comment]
Hi, we are using demo code provided by detectron2. https://github.com/facebookresearch/detectron2/blob/main/demo/demo.py

**Comment by EladDan** [comment]
@wjn922, you will also have to add the following lines into setup_cfg() in demo.py:
```
cfg = get_cfg()
from ldet.engine import add_copypaste_config  # addition
add_copypaste_config(cfg)  # addition
cfg.merge_from_file(args.config_file)
```

**Comment by wjn922** [comment]
Thanks.
