### ISSUE TITLE
why mask-rcnn-p not work?

### ISSUE THREAD

**Issue by wjn922** [ksaito-ut/openworld_ldet#3]
Hi, 
I notice that the performance of  Mask-RCNN-P is very similar to the vanilla Mask-RCNN in table 1. Is there any reason why the pseudo label method like OWOD didn't work?

**Comment by ksaito-ut** [comment]
I am not sure about a clear reason. But, it may be because the baseline we used is too simple. We may need something to ensure the quality of the pseudo label.

**Comment by wjn922** [comment]
OK, thanks.
